// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function let_(prom, cb) {
  return prom.then(Curry.__1(cb));
}

function resolve(a) {
  return Promise.resolve(a);
}

exports.let_ = let_;
exports.resolve = resolve;
/* No side effect */
