// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Async$AsyncAwait = require("./Async.bs.js");
var Swapi$AsyncAwait = require("./Swapi.bs.js");

function go(param) {
  console.log("Here's some JSON of a person");
  return Async$AsyncAwait.let_(Swapi$AsyncAwait.getPerson(/* () */0), (function (json) {
                console.log("Here is the person Json", json);
                return Async$AsyncAwait.resolve(/* () */0);
              }));
}

go(/* () */0);

exports.go = go;
/*  Not a pure module */
