// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Got = require("got");

function getPerson(param) {
  return Got("https://swapi.co/api/people/1", {
                responseType: "json"
              }).then((function (response) {
                return Promise.resolve(response.body);
              }));
}

exports.getPerson = getPerson;
/* got Not a pure module */
